version: '3.8'

services:
  db:
    image: "postgres"
    env_file: .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    networks:
      - db

  db_up:
    image: "amacneil/dbmate"
    env_file: .env
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DATABASE?sslmode=disable
    restart: on-failure
    depends_on:
      - db
    command: up
    volumes:
      - ./db/:/db
    networks:
      - db

  bot:
    build: .
    restart: always
    depends_on:
      - db_up
      - db
    env_file: .env
    environment:
      - DB_STRING=host=db port=5432 user=$POSTGRES_USER dbname=$POSTGRES_DATABASE password=$POSTGRES_PASSWORD
    networks:
      - db

volumes:
  db-data:

networks:
  db:
