name:                calamity-bot
version:             0.0.0
github:              "nitros12/calamity-bot"
homepage:            https://github.com/nitros12/calamity-bot
bug-reports:         https://github.com/nitros12/calamity-bot/issues
license:             MIT
license-file:        LICENSE
author:              "Ben Simms"
maintainer:          "ben@bensimms.moe"
copyright:           2019 Ben Simms
category:            Bots
build-type:          Simple
extra-doc-files:
  - README.md
  - CHANGELOG.md
tested-with:         GHC == 8.8.2


synopsis:            A discord bot
description:         A discord bot


dependencies:
  - base-noprelude >= 4.12 && < 5
  - relude ^>= 0.7
  - calamity ^>= 0.1.11.1
  - di-polysemy ^>= 0.1
  - polysemy ^>= 1.3
  - polysemy-plugin ^>= 0.2
  - lens ^>= 4.19
  - generic-lens ^>= 2
  - text ^>= 1.2
  - text-show ^>= 3.8
  - unordered-containers ^>= 0.2.10
  - squeal-postgresql ^>= 0.6
  - arbor-lru-cache ^>= 0.1
  - bytestring ^>= 0.10
  - uuid-types ^>= 1.0
  - generics-sop ^>= 0.5
  - time ^>= 1.9
  - hourglass ^>= 0.2
  - megaparsec ^>= 8.0
  - replace-megaparsec ^>= 1.4
  - fuzzy-dates-megaparsec ^>= 0.1

when:
  condition: flag(smuggler2)
  dependencies:
    - smuggler2 ^>= 0.3

flags:
  smuggler2:
    default: False
    manual: True

executables:
  calamity-bot:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -fplugin=Polysemy.Plugin
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wcompat
      - -Widentities
      - -Wredundant-constraints
      - -fhide-source-paths
      - -Wmissing-export-lists
      - -Wpartial-fields
      - -fno-warn-unused-do-bind
    dependencies:
      - calamity-bot
      - optparse-applicative

library:
  when:
    condition: flag(smuggler2)
    ghc-options:
      - -fplugin=Smuggler2.Plugin
  ghc-options:
    - -fplugin=Polysemy.Plugin
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wcompat
    - -Widentities
    - -Wredundant-constraints
    - -fhide-source-paths
    - -Wmissing-export-lists
    - -Wpartial-fields
    - -fno-warn-unused-do-bind
  source-dirs: src

default-extensions:
  - IncoherentInstances
  - TemplateHaskell
  - RecursiveDo
  - AllowAmbiguousTypes
  - BlockArguments
  - NoMonomorphismRestriction
  - BangPatterns
  - BinaryLiterals
  - UndecidableInstances
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveAnyClass
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - DuplicateRecordFields
  - TypeOperators
  - TypeApplications
  - RoleAnnotations
  - PatternSynonyms
