name:                calamity-bot
version:             0.0.0
github:              "nitros12/calamity-bot"
homepage:            https://github.com/nitros12/calamity-bot
bug-reports:         https://github.com/nitros12/calamity-bot/issues
license:             MIT
license-file:        LICENSE
author:              "Ben Simms"
maintainer:          "ben@bensimms.moe"
copyright:           2019 Ben Simms
category:            Bots
build-type:          Simple
extra-doc-files:
  - README.md
  - CHANGELOG.md
tested-with:         GHC == 8.8.2


synopsis:            A discord bot
description:         A discord bot


dependencies:
  - name: base
    version: ">= 4.12 && < 5"
    mixin:
      - hiding (Prelude)
  - name: relude
    version: "^>= 0.7"
    mixin:
      - (Relude as Prelude, Relude.Unsafe, Relude, Relude.Extra)
  - calamity ^>= 0.1.20
  - di ^>= 1.3
  - di-core ^>= 1.0
  - di-polysemy ^>= 0.2
  - polysemy ^>= 1.3
  - polysemy-plugin ^>= 0.2
  - lens ^>= 4.19
  - generic-lens ^>= 2
  - text ^>= 1.2
  - text-show ^>= 3.8
  - unordered-containers ^>= 0.2.10
  - beam-core ^>= 0.9
  - beam-postgres ^>= 0.5
  - arbor-lru-cache ^>= 0.1
  - bytestring ^>= 0.10
  - time ^>= 1.9
  - hourglass ^>= 0.2
  - megaparsec ^>= 8.0
  - replace-megaparsec ^>= 1.4
  - fuzzy-dates-megaparsec ^>= 0.1
  - table-layout ^>= 0.9
  - postgresql-simple ^>= 0.6
  - resource-pool ^>= 0.2
  - immortal ^>= 0.3
  - reanimate ^>= 0.4
  - reanimate-svg ^>= 0.10
  - process ^>= 1.6
  - filepath ^>= 1.4
  - data-default-class ^>= 0.1
  - emojis ^>= 0.1
  - JuicyPixels ^>= 3.3
  - linear ^>= 1.21
  - mime-types ^>= 0.1
  - wreq ^>= 0.5
  - process-extras ^>= 0.7
  - directory ^>= 1.3
  - temporary ^>= 1.3

executables:
  calamity-bot:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -O2
      - -fspecialise-aggressively
      - -flate-specialise
      - -fplugin=Polysemy.Plugin
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wincomplete-uni-patterns
      - -Wincomplete-record-updates
      - -Wcompat
      - -Widentities
      - -Wredundant-constraints
      - -fhide-source-paths
      - -Wmissing-export-lists
      - -Wpartial-fields
      - -fno-warn-unused-do-bind
      - -eventlog
    dependencies:
      - calamity-bot
      - optparse-applicative

library:
  ghc-options:
    - -fplugin=Polysemy.Plugin
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wincomplete-record-updates
    - -Wcompat
    - -Widentities
    - -Wredundant-constraints
    - -fhide-source-paths
    - -Wmissing-export-lists
    - -Wpartial-fields
    - -fno-warn-unused-do-bind
  source-dirs: src

default-extensions:
  - StrictData
  - IncoherentInstances
  - TemplateHaskell
  - RecursiveDo
  - AllowAmbiguousTypes
  - BlockArguments
  - NoMonomorphismRestriction
  - BangPatterns
  - BinaryLiterals
  - UndecidableInstances
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - DerivingVia
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  - DeriveAnyClass
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns
  - DuplicateRecordFields
  - TypeOperators
  - TypeApplications
  - RoleAnnotations
  - PatternSynonyms
